XIncludeFile "../core/Math.pbi"
XIncludeFile "../core/Array.pbi"
XIncludeFile "../core/Attribute.pbi"
XIncludeFile "../core/Object.pbi"
XIncludeFile "../core/Perlin.pbi"
XIncludeFile "../opengl/Shader.pbi"
XIncludeFile "../opengl/Texture.pbi"
XIncludeFile "../objects/Geometry.pbi"
XIncludeFile "../objects/Vertex.pbi"
XIncludeFile "../objects/Edge.pbi"
XIncludeFile "../objects/Polygon.pbi"
XIncludeFile "../objects/Sample.pbi"
XIncludeFile "../core/Array.pbi"
XIncludeFile "../core/Utils.pbi"
; XIncludeFile "../objects/Shapes.pbi"
; XIncludeFile "../objects/Geometry.pbi"
; XIncludeFile "../objects/Topology.pbi"
; XIncludeFile "../objects/Shapes.pbi"
; XIncludeFile "../objects/Location.pbi"
; XIncludeFile "../objects/Object3D.pbi"
; XIncludeFile "../objects/Stack.pbi"
; IDE Options = PureBasic 5.62 (Windows - x64)
; CursorPosition = 13
; EnableXP